import os


EMAIL_SERVER_HOST = os.getenv("EMAIL_SERVER_HOST")
EMAIL_SERVER_PORT = os.getenv("EMAIL_SERVER_PORT")
EMAIL_SERVER_WEB_PORT = os.getenv("EMAIL_SERVER_WEB_PORT")
REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = os.getenv("REDIS_PORT")
