version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mailhog
    environment:
      - EMAIL_SERVER_HOST=mailhog
      - EMAIL_SERVER_PORT=1025
      - EMAIL_SERVER_WEB_PORT=8025
    volumes:
      - ./:/code
    ports:
      - "5005:80"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web interface
